name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 * * * *' # Vérifie toutes les heures
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  keep_alive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make an empty commit to keep the app alive
        run: |
          git config --global user.email "amelie_bua@hotmail.fr"
          git config --global user.name "Meylouu"
          git commit --allow-empty -m "Keep Streamlit App Alive"
          git push
