name: Keep Streamlit App Alive

permissions:
  contents: write
  
on:
  schedule:
    - cron: '0 * * * *' # Vérifie toutes les heures
  workflow_dispatch: # Permet de déclencher manuellement le workflow

jobs:
  keep_alive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Debug Git configuration
        run: |
          git config --list
          git remote -v

      - name: Configure Git user
        run: |
          git config --global user.email "amelie_bua@hotmail.fr"
          git config --global user.name "Meylouu"

      - name: Pull latest changes with rebase
        run: |
          git pull --rebase origin main

      - name: Make an empty commit to keep the app alive
        run: |
          git commit --allow-empty -m "Keep Streamlit App Alive"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}